package com.example.fitgenius.service;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

// --- Helper classes for JSON deserialization ---

/**
 * Represents the structure of the part within a content block.
 * We only care about the 'text' part in this case.
 */
record Part(String text) {}

/**
 * Represents a candidate response generated by the model.
 */
record Candidate(Content content) {}

/**
 * Represents the structured content of the response.
 */
record Content(List<Part> parts) {}


/**
 * The top-level class representing the full response from the Gemini API.
 */
public record GeminiResponse(List<Candidate> candidates) {

    /**
     * Extracts the generated text from the first candidate.
     * @return The extracted text or an empty string if not found.
     */
    public String getGeneratedText() {
        if (candidates != null && !candidates.isEmpty()) {
            Candidate firstCandidate = candidates.get(0);
            if (firstCandidate.content() != null && firstCandidate.content().parts() != null && !firstCandidate.content().parts().isEmpty()) {
                return firstCandidate.content().parts().get(0).text();
            }
        }
        return "Sorry, I couldn't generate a response. Please try again.";
    }
}

/**
 * Represents the structure for the system instruction in the API request body.
 */
record SystemInstruction(List<Part> parts) {}

/**
 * Represents the request body for the Gemini API, using the dedicated systemInstruction field.
 */
record GeminiRequest(
        List<Content> contents,
        @JsonProperty("systemInstruction") SystemInstruction systemInstruction
) {}